// src/lib/components/widgets/scroll-up.svelte
<script lang="ts">
	import Button from '$lib/components/ui/button/button.svelte';
	import { ChevronUp } from 'lucide-svelte';
	import { onMount } from 'svelte';
	import { cn } from '$lib/utils';

	let visible = false;

	onMount(() => {
		const handleScroll = () => {
			visible = window.scrollY > 200;
		};

		window.addEventListener('scroll', handleScroll);
		return () => window.removeEventListener('scroll', handleScroll);
	});

	const scrollToTop = () => {
		window.scrollTo({ top: 0, behavior: 'smooth' });
	};
</script>

<Button
	class={cn(
		'fixed bottom-4 right-4 p-2 shadow-md transition-all duration-300 z-50',
		!visible && 'opacity-0 pointer-events-none translate-y-16'
	)}
	variant="secondary"
	size="icon"
	onclick={scrollToTop}
	aria-label="Scroll to top"
>
	<ChevronUp class="h-6 w-6" />
</Button>

// src/components/widgets/ScrollUp.tsx
import React, { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button.tsx';
import { ChevronUp } from 'lucide-react';

const ScrollUp: React.FC = () => {
  const [isVisible, setIsVisible] = useState(false);

  useEffect(() => {
    const toggleVisibility = () => {
      if (window.pageYOffset > 300) {
        setIsVisible(true);
      } else {
        setIsVisible(false);
      }
    };

    window.addEventListener('scroll', toggleVisibility);

    return () => window.removeEventListener('scroll', toggleVisibility);
  }, []);

  const scrollToTop = () => {
    window.scrollTo({
      top: 0,
      behavior: 'smooth'
    });
  };

  if (!isVisible) {
    return null;
  }

  return (
    <Button
      className="fixed bottom-4 right-4 p-2 rounded-full shadow-md"
      onClick={scrollToTop}
      aria-label="Scroll to top"
    >
      <ChevronUp className="h-6 w-6" />
    </Button>
  );
};

export default ScrollUp;
